[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "xilophor"
name = "StaticNetcodeLib"
description = "A library/patcher for NGO in a static context."
websiteUrl = "https://github.com/Xilophor/StaticNetcodeLib"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Lordfirespeed-OdinSerializer = "2022.11.9"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LethalNetworkAPI/bin/Release/netstandard2.1/StaticNetcodeLib.dll"
target = "/BepInEx/plugins/StaticNetcodeLib/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "libraries", "serverside", "clientside" ]
